#pragma once
#include <stdint.h>
enum { VK_ITF_AUDIO_CONTROL, VK_ITF_AUDIO_STREAM, VK_ITF_AUDIO_PLAYBACK, VK_ITF_HID, VK_ITF_COUNT };
#define VK_EP_AUDIO 0x81
#define VK_EP_HID 0x82
extern const uint8_t vk_configuration_descriptor[];
extern const uint8_t vk_hid_descriptor[];

#define VK_EP_PLAYBACK 0x03
#define VK_EP_FEEDBACK 0x83
#define VK_AUDIO_DESC_LEN (TUD_AUDIO_MIC_ONE_CH_DESC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN + 2*TUD_AUDIO_DESC_STD_AS_INT_LEN + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN + TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN)

#define VK_DIAGNOSTIC_SIZE 96
